[package]
name = "polars_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.43.1", features = ["lazy","sql"] }
struct_iterable = "0.1.1"
